<?php
ZN_Field::edit
(
	$_GET['id'], 
	$_POST['name'], 
	$_POST['identified'], 
	$_POST['type_id'], 
	$_POST['desc'], 
	$_POST['null'], 
	$_POST['default'],
	$_POST['foreign_change'],
	$_POST['is_order']
);
redirect("/".Reg::url_creator()."/field/list/?entity_id={$entity['ID']}");
?>
