<html>
	<head>
		<title>Какой то заголовок</title>
		<style type="text/css">
		TABLE TD
		{
			vertical-align: middle;
			text-align: center;
			border: 1px solid green;
		}
		</style>
	</head>
	<body>
		<table align="center" width="100%">
			<tr>
				<td colspan="2">
					<!--zn_menu_top-->Верхнее меню
				</td>
			</tr>
			<tr>
				<td width="30%" height="100">
					<!--zn_menu_left-->Левое меню
				</td>
				<td width="70%" rowspan="2">
					<!--zn_tovar_desc-->Описание товара
				</td>
			</tr>
			<tr>
				<td height="100">
					<!--zn_news_last-->Последние новости
				</td>
			</tr>
		</table>
	</body>
</html>
