<form method="post" action="/<?php echo Reg::url_creator(); ?>/entity/delete/?id=<?php echo $data['id']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td align="center" colspan="2">Вы действительно хотите удалить сущность "<?php echo $data['name']; ?>" ?</td>
		</tr>
		<tr>
			<td align="right">
				<input type="submit" value="Да" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/entity/list/?pack_id=<?php echo $data['pack']['ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>