<form method="post" action="/<?php echo Reg::url_creator(); ?>/entity/edit/?id=<?php echo $entity['ID']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td width="50%" align="right">Наименование</td>
			<td width="50%" align="left"> 
				<input type="text" name="name" value="<?php echo $fdata['name']; ?>"/>
				<?php echo Helper::warn("name"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">Идентификатор</td>
			<td align="left">
				<input type="text" name="identified" value="<?php echo $fdata['identified']; ?>"/>
				<?php echo Helper::warn("identified"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">Описание</td>
			<td>
				<textarea name="desc"><?php echo $fdata['desc']; ?></textarea>
				<?php echo Helper::warn("desc"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">
				<input type="submit" value="Изменить" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/entity/list/?pack_id=<?php echo $pack['ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>