<form method="post" action="/<?php echo Reg::url_creator(); ?>/entity/insert/?id=<?php echo $entity['ID']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td width="50%" align="right">Укажите необходимое кол-во строк</td>
			<td width="50%" align="left">
				<input type="text" name="count" value="<?php echo $fdata['count']; ?>"/>
				<?php echo Helper::warn("count"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">
				<input type="submit" value="Добавить" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/entity/list/?pack_id=<?php echo $entity['Pack_ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>