<form method="post" action="/<?php echo Reg::url_creator(); ?>/entity/php/?id=<?php echo $entity['ID']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td align="center" colspan="2">Создать новый класс для "<?php echo $entity['Name']; ?>".</td>
		</tr>
		<tr>
			<td width="50%" align="right">Заменить старый файл</td>
			<td width="50%" align="left"> 
				<input type="hidden" name="replace" value="0"/>
				<input style="width: 10px;" type="checkbox" name="replace" value="1"<?php if($fdata['replace']==1): ?> checked="checked"<?php endif; ?>/>
			</td>
		</tr>
		<tr>
			<td align="right">
				<input type="submit" value="Создать" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/entity/list/?pack_id=<?php echo $entity['Pack_ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>