<p class="title">Добавить уникальный ключ к сущности "<?php echo $entity['Name']; ?>".</p>

<form method="post" action="/<?php echo Reg::url_creator(); ?>/unique/add/?entity_id=<?php echo $entity['ID']; ?>">
	<table class="list" width="80%" align="center">
		<colgroup>
			<col width="45%" />
			<col width="45%" />
			<col width="10%" />
		</colgroup>
		<thead>
			<tr>
				<th>Наименование</th>
				<th>Идентификатор</th>
				<th>Выбор</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($field as $val): ?>
			<tr>
				<td>
					<?php echo $val['Name']; ?>
				</td>
				<td>
					<?php echo $val['Identified']; ?>
				</td>
				<td>
					<input type="checkbox" style="width: 10px;"
						   name="field_check[]"
						   value="<?php echo $val['ID']; ?>"
						   <?php if($val['check']): ?>checked="checked"<?php endif; ?>
					/>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<br/>
	<table width="80%" class="forma" align="center">
		<tr>
			<td align="right">
				<input type="submit" value="Добавить" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/field/list/?entity_id=<?php echo $entity['ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>