<form method="post" action="/<?php echo Reg::url_creator(); ?>/unique/delete/?id=<?php echo $unique['id']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td align="center" colspan="2">Вы действительно хотите удалить уникальный ключ "<?php echo $unique['name']; ?>" ?</td>
		</tr>
		<tr>
			<td align="right">
				<input type="submit" value="Да" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/field/list/?entity_id=<?php echo $entity['ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>