<form method="post" action="/<?php echo Reg::url_creator(); ?>/enum/delete/?id=<?php echo $enum['ID']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td align="center" colspan="2">Вы действительно хотите удалить перечисление "<?php echo $enum['Name']; ?>" ?</td>
		</tr>
		<tr>
			<td align="right">
				<input type="submit" value="Да" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/enum/list/?field_id=<?php echo $field['ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>