<form method="post" action="/<?php echo Reg::url_creator(); ?>/enum/edit/?id=<?php echo $data['id']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td width="50%" align="right">Наименование</td>
			<td width="50%" align="left"> 
				<input type="text" name="name" value="<?php echo $data['name']; ?>"/>
				<?php echo Helper::warn("name"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">
				<input type="submit" value="Изменить" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/enum/list/?field_id=<?php echo $data['field']['ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>