<form method="post" action="/<?php echo Reg::url_creator(); ?>/field/edit/?id=<?php echo $field['ID']; ?>">
	<table width="90%" class="forma" align="center">
		<tr>
			<td width="50%" align="right">Наименование</td>
			<td width="50%" align="left"> 
				<input type="text" id="name" name="name" value="<?php echo $fdata['name']; ?>"/>
				<?php echo Helper::warn("name"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">Идентификатор</td>
			<td align="left">
				<input type="text" id="identified" name="identified" value="<?php echo $fdata['identified']; ?>"/>
				<?php echo Helper::warn("identified"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">Тип</td>
			<td align="left">
				<?php if(in_array($field['type'], array("id","sort","enum","foreign"))): ?>
					<input type="hidden" name="type_id" value="<?php echo $field['Type_ID']; ?>"/>
				<?php endif; ?>
				<select id="type_id" name="type_id" style="width: 200px;">
					<?php foreach ($type as $val): ?>
						<option value="<?php echo $val['ID']; ?>" 
								<?php if($val['ID'] == $fdata['type_id']): ?>selected="selected"<?php endif; ?>
								about="<?php echo $val['Desc']; ?>"
						>
							<?php echo $val['Identified']; ?>
						</option>
					<?php endforeach; ?>
				</select>
				<img id="img_type_about" src="/<?php echo Reg::url_creator(); ?>/file.php?path=img/about.png" width="24" height="24" style="cursor: pointer; margin: 0 0 -6px 10px;" title="" />
				<?php echo Helper::warn("type_id"); ?>
			</td>
		</tr>
		<tr>
			<td align="right">Описание</td>
			<td>
				<textarea name="desc"><?php echo $fdata['desc']; ?></textarea>
				<?php echo Helper::warn("desc"); ?>
			</td>
		</tr>
		<tr id="tr_null">
			<td align="right">NULL</td>
			<td>
				<input type="hidden" name="null" value="0"/>
				<input style="width: 10px;" type="checkbox" name="null" value="1"<?php if($fdata['null']==true): ?> checked="checked"<?php endif; ?>/>
			</td>
		</tr>
		
		<!--Поле по умолчанию-->
		<tr id="tr_default">
			<td align="right">По умолчанию</td>
			<td align="left">
				<input type="text" name="default" value="<?php echo $fdata['default']; ?>"/>
				<?php echo Helper::warn("default"); ?>
			</td>
		</tr>
		
		<!--Перечисления-->
		<tr id="tr_default_enum">
			<td align="right">По умолчанию</td>
			<td align="left">
				
				<?php if(!empty($enum)): ?>
					<select name="default" style="width: 200px;">
						<option value=""></option>
						<?php foreach ($enum as $e_val): ?>
							<option value="<?php echo $e_val['Name']; ?>"
									<?php if($fdata['default'] == $e_val['Name']): ?> selected="selected"<?php endif; ?>
							>
								<?php echo $e_val['Name']; ?>
							</option>
						<?php endforeach; ?>
					</select>
				<?php endif; ?>
				
			</td>
		</tr>
		
		<!--Внешний ключ-->
		<input type="hidden" name="foreign_change" value="0"/>
		<?php if($field['type'] == "foreign"): ?>
			<tr id="tr_foreign">
				<td align="right">Внешний ключ</td>
				<td>
					<?php if($entity['Pack_ID'] != $ref_pack['ID']): ?>
						<?php echo $ref_pack['Name']; ?> \ <?php echo $ref_entity['Name']; ?> (<?php echo $ref_field['Identified']; ?>)
					<?php else: ?>
						<?php echo $ref_entity['Name']; ?> (<?php echo $ref_field['Identified']; ?>)
					<?php endif; ?>
				</td>
			</tr>
			
			<tr id="tr_foreign_change">
				<td align="right">Изменяемый внешний ключ</td>
				<td>
					<input type="checkbox" name="foreign_change" id="foreign_change" style="width: 10px;" value="1"<?php if($fdata['foreign_change']=="1"): ?> checked="checked"<?php endif; ?>/>
				</td>
			</tr>
		<?php endif; ?>
		
		<tr id="tr_is_order">
			<td align="right">Использовать в сортировке</td>
			<td>
				<input type="hidden" name="is_order" value="0"/>
				<input style="width: 10px;" type="checkbox" name="is_order" value="1"<?php if($fdata['is_order']=="1"): ?> checked="checked"<?php endif; ?>/>
			</td>
		</tr>
			
		<tr>
			<td align="right">
				<input type="submit" value="Изменить" class="knopka"/> 
			</td>
			<td align="left">
				<a href="/<?php echo Reg::url_creator(); ?>/field/list/?entity_id=<?php echo $entity['ID']; ?>">
					<input type="button" value="Назад" class="knopka"/>
				</a>
			</td>
		</tr>
	</table>
</form>