<p class="title">Поля сущностей "<?php echo $entity['Name']; ?>"</p>
<table width="90%" class="list" align="center">
	<colgroup>
		<col width="30%" />
		<col width="25%" />
		<col width="15%" />
		<col width="10%"/>
		<col width="10%" />
		<col width="10%" />
	</colgroup>
	<thead>
		<tr>
			<th>Наименование</th>
			<th>Идентификатор</th>
			<th>Тип</th>
			<th>Ред.</th>
			<?php if(count($field) > 1): ?>
			<th>Сорт.</th>
			<?php endif; ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($field as $key=>$val): ?>
			<tr>
				<td>
					<?php echo $val['Name']; ?>
				</td>
				<td>
					<?php echo $val['Identified']; ?>
					<?php if($val['Is_Order'] == "1"): ?>
					&nbsp;(order)
					<?php endif; ?>
				</td>
				<td>
					<?php if($val['type_identified'] == "enum"): ?>
						<a title="Перечисления" href="/<?php echo Reg::url_creator(); ?>/enum/list/?field_id=<?php echo $val['ID']; ?>">
							<?php echo $val['type_identified']; ?>
						</a>
					<?php else : ?>
						<?php echo $val['type_identified']; ?>
					<?php endif; ?>
				</td>
				<td>
					<a href="/<?php echo Reg::url_creator(); ?>/field/edit/?id=<?php echo $val['ID']; ?>">Ред.</a>
					&nbsp;/&nbsp;
					<a href="/<?php echo Reg::url_creator(); ?>/field/delete/?id=<?php echo $val['ID']; ?>">Уд.</a>
				</td>
				<?php if(count($field) > 1): ?>
					<td>
						<?php if($key != 0): ?>
						<a href="/<?php echo Reg::url_creator(); ?>/field/sort_up/?id=<?php echo $val['ID']; ?>">&DoubleUpArrow;</a>
						<?php endif; ?>


						<?php if($key != count($field)-1): ?>
						<a href="/<?php echo Reg::url_creator(); ?>/field/sort_down/?id=<?php echo $val['ID']; ?>">&DoubleDownArrow;</a>
						<?php endif; ?>
					</td>
				<?php endif; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<br/>
<center>
	<a href="/<?php echo Reg::url_creator(); ?>/field/add/?entity_id=<?php echo $entity['ID']; ?>">
		<input type="button" value="Добавить" class="knopka"/>
	</a>
	<a href="/<?php echo Reg::url_creator(); ?>/entity/list/?pack_id=<?php echo $pack['ID']; ?>">
		<input type="button" value="Назад" class="knopka"/>
	</a>
</center>
<br/><br/>
<!-- Уникальные ключи -->
<p class="title">Уникальные ключи</p>
<?php if(!empty($unique)): ?>
	<table width="90%" class="list" align="center">
		<colgroup>
			<col width="45%" />
			<col width="35%" />
			<col width="20%" />
		</colgroup>
		<thead>
			<tr>
				<th>Наименование</th>
				<th>Поля</th>
				<th>Ред.</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($unique as $val): ?>
			<tr>
				<td>
					<?php echo $val['name']; ?>
				</td>
				<td>
					<?php if(!empty($val['field'])): ?>
						<?php foreach ($val['field'] as $f_key=>$f_val): ?>
							<?php echo $f_val['Identified']; ?><?php if(count($val['field']) != $f_key+1): ?>,<?php endif; ?>
						<?php endforeach; ?>
					<?php endif; ?>
				</td>
				<td>
					<a href="/<?php echo Reg::url_creator(); ?>/unique/delete/?id=<?php echo $val['id']; ?>">Уд.</a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>
<br/>
<center>
	<a href="/<?php echo Reg::url_creator(); ?>/unique/add/?entity_id=<?php echo $entity['ID']; ?>">
		<input type="button" value="Добавить" class="knopka"/>
	</a>
</center>